# Classification

## Team Name
>### Sigma  

## Team Member
>### 조현윤, 이상협, 정하연  

## Objective
> ### in search of better methods of using this behavioral data to predict which individuals they should approach—and even when and how to approach them.
> ### to create a classification algorithm that accurately identifies which customers have the most potential business value for Red Hat based on their characteristics and activities.
> ### to predict the potential business value of a person who has performed a specific activity.

## Evaluation
> ### valuated on area under the ROC curve between the predicted and the observed outcome.

## Submission File
> ### For each activity_id in the test set, you must predict a probability for the 'outcome' variable, represented by a number between 0 and 1.
~~~~
activity_id,outcome
act1_1,0
act1_100006,0
act1_100050,0
~~~~

## Data
> ### uses two separate data files that may be joined together to create a single, unified data table: a people file and an activity file.
> ### The people file contains all of the unique people (and the corresponding characteristics) that have performed activities over time. Each row in the people file represents a unique person. Each person has a unique people_id.
> ### The activity file contains all of the unique activities (and the corresponding activity characteristics) that each person has performed over time. Each row in the activity file represents a unique activity performed by a person on a certain date. Each activity has a unique activity_id.
> ### The activity file contains several different categories of activities. 
>> Type 1 activities are different from type 2-7 activities because there are more known characteristics associated with type 1 activities (nine in total) than type 2-7 activities (which have only one associated characteristic).
> ### To develop a predictive model with this data, you will likely need to join the files together into a single data set. The two files can be joined together using person_id as the common key. All variables are categorical, with the exception of 'char_38' in the people file, which is a continuous numerical variable.

## Reference 
[kaggel Predicting Red Hat Business Value](https://www.kaggle.com/c/predicting-red-hat-business-value)

### Load Python Package

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from datetime import datetime
from datetime import date
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats.api as sms
import statsmodels.stats.stattools as stools
import scipy as sp
%matplotlib inline

C:\Users\pc\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [3]:
import xgboost

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
from sklearn.metrics import *

In [7]:
from sklearn.ensemble import VotingClassifier

In [8]:
from sklearn.ensemble import GradientBoostingClassifier

In [9]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [12]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier


In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
cv =KFold(10)

## Exploratory Data Analysis (EDA )¶

## Load Data Set

In [16]:
# activity data set
act_Train = pd.read_csv('./data/act_train.csv')
act_Test = pd.read_csv('./data/act_test.csv')
# people data set
people = pd.read_csv('./data/people.csv')

### Split people data set wether train data set or test data set

In [17]:
idx_train =list(act_Train['people_id'].value_counts().index)
idx_test =list(act_Test['people_id'].value_counts().index)

In [18]:
train_people = people.loc[people['people_id'].isin(idx_train)]
test_people = people.loc[people['people_id'].isin(idx_test)]

In [19]:
train_people.to_csv('./data/act_train_people.csv',index=False)
test_people.to_csv('./data/act_test_people.csv',index=False)

In [20]:
print('Number of active people: {}'.format(act_Train['people_id'].nunique()))

Number of active people: 151295


In [21]:
print('Number of active people: {}'.format(act_Test['people_id'].nunique()))

Number of active people: 37823


In [22]:
trainMerge = pd.merge(act_Train,people, on='people_id')
trainMerge.tail()

people_id   activity_id      date_x activity_category char_1_x  \
2197286  ppl_99994  act2_4668076  2023-06-16            type 4      NaN   
2197287  ppl_99994  act2_4743548  2023-03-30            type 4      NaN   
2197288  ppl_99994   act2_536973  2023-01-19            type 2      NaN   
2197289  ppl_99994   act2_688656  2023-05-02            type 4      NaN   
2197290  ppl_99994   act2_715089  2023-06-15            type 2      NaN   

        char_2_x char_3_x char_4_x char_5_x char_6_x   ...   char_29 char_30  \
2197286      NaN      NaN      NaN      NaN      NaN   ...      True    True   
2197287      NaN      NaN      NaN      NaN      NaN   ...      True    True   
2197288      NaN      NaN      NaN      NaN      NaN   ...      True    True   
2197289      NaN      NaN      NaN      NaN      NaN   ...      True    True   
2197290      NaN      NaN      NaN      NaN      NaN   ...      True    True   

        char_31 char_32  char_33 char_34 char_35 char_36 char_37 char_38  
2197286    True    True    False    True    True    True    True      95  
2197287    True    True    False    True    True    True    True      95  
2197288    True    True    False    True    True    True    True      95  
2197289    True    True    False    True    True    True    True      95  
2197290    True    True    False    True    True    True    True      95  

[5 rows x 55 columns]

In [23]:
trainMerge.to_csv('./data/train_merge.csv',index=False)

In [24]:
testMerge = pd.merge(act_Test,people, on='people_id')
testMerge.tail()

people_id   activity_id      date_x activity_category char_1_x  \
498682  ppl_99997  act2_4367092  2023-04-22            type 2      NaN   
498683  ppl_99997  act2_4404220  2022-11-12            type 2      NaN   
498684  ppl_99997   act2_448830  2022-08-02            type 2      NaN   
498685  ppl_99997   act2_450133  2022-08-02            type 2      NaN   
498686  ppl_99997   act2_847967  2022-10-15            type 2      NaN   

       char_2_x char_3_x char_4_x char_5_x char_6_x   ...   char_29 char_30  \
498682      NaN      NaN      NaN      NaN      NaN   ...     False   False   
498683      NaN      NaN      NaN      NaN      NaN   ...     False   False   
498684      NaN      NaN      NaN      NaN      NaN   ...     False   False   
498685      NaN      NaN      NaN      NaN      NaN   ...     False   False   
498686      NaN      NaN      NaN      NaN      NaN   ...     False   False   

       char_31 char_32 char_33 char_34 char_35 char_36 char_37 char_38  
498682   False   False   False   False   False   False   False      36  
498683   False   False   False   False   False   False   False      36  
498684   False   False   False   False   False   False   False      36  
498685   False   False   False   False   False   False   False      36  
498686   False   False   False   False   False   False   False      36  

[5 rows x 54 columns]

In [25]:
testMerge.to_csv('./data/test_merge.csv',index=False)

In [26]:
dfx = act_Train.groupby(['people_id','outcome']).size().unstack()
dfx = dfx.fillna(0).astype(int)

In [27]:
only1 = dfx[(dfx[0]==0) & (dfx[1]!=0)]
only0 = dfx[(dfx[0]!=0) & (dfx[1]==0)]
mix_0or1 = dfx[(dfx[0]!=0) & (dfx[1]!=0)]

In [28]:
print (len(only1.index),len(only0.index),len(mix_0or1))

62115 82524 6656


In [29]:
train_People = pd.merge(train_people, dfx, left_on = 'people_id',right_index = True)

In [30]:
train_People.rename(columns={0:'outcome_0',1:'outcome_1'}, inplace = True)

In [31]:
def ax(x):
    if x['outcome_0'] !=0 and x['outcome_1'] ==0:
        return 0
    elif x['outcome_0'] ==0 and x['outcome_1'] !=0:
        return 1
    else:
        return 2

In [32]:
train_People.head()

people_id  char_1      group_1  char_2        date   char_3   char_4  \
0     ppl_100  type 2  group 17304  type 2  2021-06-29   type 5   type 5   
1  ppl_100002  type 2   group 8688  type 3  2021-01-06  type 28   type 9   
2  ppl_100003  type 2  group 33592  type 3  2022-06-10   type 4   type 8   
4  ppl_100006  type 2   group 6534  type 3  2022-07-27  type 40  type 25   
7  ppl_100013  type 2   group 4204  type 3  2023-01-24   type 4   type 8   

   char_5  char_6   char_7    ...     char_31 char_32  char_33  char_34  \
0  type 5  type 3  type 11    ...        True   False    False     True   
1  type 5  type 3  type 11    ...        True    True     True     True   
2  type 5  type 2   type 5    ...        True    True     True     True   
4  type 9  type 3   type 8    ...        True   False    False    False   
7  type 4  type 1   type 7    ...        True    True     True     True   

   char_35  char_36  char_37  char_38  outcome_0  outcome_1  
0     True     True    False       36          6          0  
1     True     True    False       76          0          2  
2    False     True     True       99          0         34  
4     True     True    False       84          0          3  
7    False     True     True       91          0          5  

[5 rows x 43 columns]

In [34]:
train_People['result'] = train_People.apply(ax, axis = 1)

In [35]:
X = train_People.drop(['people_id','outcome_0', 'outcome_1','result'],axis = 1)
y = train_People['result']
#151295

In [36]:
np.any(X != np.NaN)

True

In [37]:
for idx in X.columns:
    #X[idx] = X[idx].fillna('type 0')
    X[idx] = LabelEncoder().fit_transform(X[idx])

In [38]:
X.tail()

char_1  group_1  char_2  date  char_3  char_4  char_5  char_6  char_7  \
189111       1     4691       1   981      38      20       4       1      20   
189113       0    28923       0   682      33      21       3       2       2   
189114       1     4691       1  1009      39      11       7       2       2   
189115       1     4691       1    38      38      20       2       3       7   
189116       1     5064       2   961      11      22       1       0      11   

        char_8   ...     char_29  char_30  char_31  char_32  char_33  char_34  \
189111       7   ...           0        0        0        1        0        1   
189113       1   ...           0        0        0        1        0        1   
189114       2   ...           0        0        0        0        0        0   
189115       2   ...           0        0        0        0        0        0   
189116       1   ...           1        1        1        1        0        1   

        char_35  char_36  char_37  char_38  
189111        0        1        1        3  
189113        0        1        1       89  
189114        0        0        0        0  
189115        0        0        0        0  
189116        1        1        1       95  

[5 rows x 40 columns]

In [56]:
logimodel = LogisticRegression().fit(X,y)

In [62]:
cross_val_score(logimodel, X, y, scoring='accuracy',cv=cv)

array([ 0.81949769,  0.81962987,  0.8236616 ,  0.82181097,  0.82313285,
        0.81975015,  0.81968405,  0.81657743,  0.81690793,  0.82265847])

In [63]:
qda = QuadraticDiscriminantAnalysis(store_covariances = True).fit(X,y)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [64]:
cross_val_score(qda, X, y, scoring='accuracy',cv=cv)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-pa

array([ 0.48360872,  0.47402512,  0.59391937,  0.49345671,  0.57224058,
        0.7880891 ,  0.65820609,  0.48079847,  0.49329103,  0.70963051])

In [65]:
lda = LinearDiscriminantAnalysis(n_components=3, solver="svd", store_covariance=True).fit(X, y)
cross_val_score(lda, X, y, scoring='accuracy',cv=cv)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)


array([ 0.81996034,  0.82233972,  0.81857237,  0.81705221,  0.81665565,
        0.81875868,  0.82358385,  0.82127041,  0.81875868,  0.82298896])

In [66]:
clf_norm = GaussianNB().fit(X,y)
cross_val_score(clf_norm, X, y, scoring='accuracy',cv=cv)

array([ 0.68830139,  0.68559154,  0.68744217,  0.6849306 ,  0.67699934,
        0.68649613,  0.68530637,  0.68001851,  0.67988631,  0.67763897])

In [67]:
clf_bern = BernoulliNB().fit(X, y)
cross_val_score(clf_bern, X, y, scoring='accuracy',cv=cv)

array([ 0.6784534 ,  0.67514871,  0.67805684,  0.67448777,  0.66794448,
        0.67572212,  0.6766475 ,  0.67155794,  0.66759204,  0.67129354])

In [68]:
clf_mult = MultinomialNB().fit(X,y)
cross_val_score(clf_mult, X, y, scoring='accuracy',cv=cv)

array([ 0.48770654,  0.48955717,  0.48420357,  0.47904825,  0.4849306 ,
        0.48998612,  0.48767268,  0.48139335,  0.49375372,  0.48628462])

In [77]:
tree1 = DecisionTreeClassifier(criterion='entropy', max_depth=1).fit(X, y)
cross_val_score(tree1, X, y, scoring='accuracy',cv=cv)

array([ 0.82009253,  0.82214144,  0.81837409,  0.81771315,  0.81982816,
        0.81889087,  0.82318726,  0.82100601,  0.82047723,  0.82252627])

In [80]:
bagging = BaggingClassifier(DecisionTreeClassifier(), bootstrap_features=True, random_state=0).fit(X, y)
cross_val_score(bagging, X, y, scoring='accuracy',cv=cv)

array([ 0.87891606,  0.88162591,  0.88023794,  0.87779247,  0.87680106,
        0.87599974,  0.87950294,  0.87837927,  0.87593364,  0.87751999])

In [81]:
extraforest = ExtraTreesClassifier(n_estimators=150, random_state=0).fit(X,y)
cross_val_score(extraforest, X, y, scoring='accuracy',cv=cv)

array([ 0.87561137,  0.88056841,  0.87514871,  0.87686715,  0.87607403,
        0.87309141,  0.87904025,  0.87282702,  0.87408289,  0.87117457])

In [82]:
forest = RandomForestClassifier(n_estimators = 150).fit(X,y)
cross_val_score(forest, X, y, scoring='accuracy',cv=cv)

array([ 0.87904825,  0.88446794,  0.87713153,  0.87627231,  0.87600793,
        0.87791658,  0.88082491,  0.87414899,  0.87646242,  0.87414899])

In [86]:
model_ada = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5, random_state=0), 
                               algorithm="SAMME", n_estimators=100).fit(X,y)
cross_val_score(model_ada, X, y, scoring='accuracy',cv=cv)

NameError: name 'AdaBoostClassifier' is not defined

In [ ]:
model_grad = GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=0).fit(X,y)
cross_val_score(model_grad, X, y, scoring='accuracy',cv=cv)

In [35]:
model_xgb = xgboost.XGBClassifier(n_estimators=100, max_depth=10)
%time
Xx = model_xgb.fit(X,y)

Wall time: 0 ns


In [36]:
for ix in range(len(X.columns)):
    print (X.columns[ix], Xx.feature_importances_[ix])

char_1 0.00996145
group_1 0.272938
char_2 0.00406065
date 0.142657
char_3 0.054752
char_4 0.0442251
char_5 0.03376
char_6 0.0334002
char_7 0.0752197
char_8 0.0320535
char_9 0.0323619
char_10 0.00654845
char_11 0.00821383
char_12 0.00645592
char_13 0.00734002
char_14 0.00580828
char_15 0.00571575
char_16 0.00547931
char_17 0.00473914
char_18 0.00728861
char_19 0.00499615
char_20 0.00493446
char_21 0.00400925
char_22 0.00479054
char_23 0.00612696
char_24 0.0074531
char_25 0.00924184
char_26 0.00632228
char_27 0.00576715
char_28 0.00217939
char_29 0.00643536
char_30 0.00539707
char_31 0.00688769
char_32 0.00533539
char_33 0.00572603
char_34 0.0059008
char_35 0.00723721
char_36 0.00457466
char_37 0.00392701
char_38 0.099779


In [37]:
actX = act_Train.drop(['people_id','activity_id','outcome'],axis = 1)
acty = act_Train['outcome']

In [38]:
for idx in actX.columns:
    actX[idx] = actX[idx].fillna('type 0')
    actX[idx] = LabelEncoder().fit_transform(actX[idx])

In [69]:
logimodel_act = LogisticRegression().fit(actX,acty)

In [70]:
cross_val_score(logimodel_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.61977427,  0.50443046,  0.51324131,  0.51512545,  0.53869084,
        0.63643397,  0.52123752,  0.6305722 ,  0.57515849,  0.48487455])

In [71]:
qda_act= QuadraticDiscriminantAnalysis(store_covariances = True).fit(actX,acty)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)


In [72]:
cross_val_score(qda_act, actX, acty, scoring='accuracy',cv=cv)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to

array([ 0.39371501,  0.50752973,  0.50146317,  0.4968757 ,  0.47854858,
        0.37569461,  0.48644922,  0.38067347,  0.43497217,  0.49541026])

In [73]:
lda_act = LinearDiscriminantAnalysis(n_components=3, solver="svd", store_covariance=True).fit(actX, acty)
cross_val_score(lda_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.61819961,  0.50453058,  0.51197156,  0.51494796,  0.53868174,
        0.63604258,  0.52119656,  0.63067688,  0.57513118,  0.48533876])

In [74]:
clf_norm_act = GaussianNB().fit(actX,acty)
cross_val_score(clf_norm_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.39244982,  0.50046648,  0.50321532,  0.49189684,  0.50147682,
        0.37361477,  0.5005211 ,  0.37857998,  0.43417573,  0.47920393])

In [75]:
clf_bern_act = BernoulliNB().fit(actX, acty)
cross_val_score(clf_bern_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.6203477 ,  0.50820329,  0.51335054,  0.51678659,  0.5408617 ,
        0.63783115,  0.52536989,  0.63180554,  0.58041497,  0.48548439])

In [76]:
clf_mult_act = MultinomialNB().fit(actX,acty)
cross_val_score(clf_mult_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.59483457,  0.50232787,  0.49638418,  0.4996837 ,  0.50401631,
        0.61737413,  0.4923838 ,  0.62836949,  0.53971483,  0.48157048])

In [78]:
tree_act = DecisionTreeClassifier(criterion='entropy', max_depth=1).fit(actX, acty)
cross_val_score(tree_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.6203477 ,  0.50820329,  0.51335054,  0.51678659,  0.5408617 ,
        0.63783115,  0.52536989,  0.63180554,  0.58041497,  0.48548439])

In [83]:
bagging_act = BaggingClassifier(DecisionTreeClassifier(), bootstrap_features=True, random_state=0).fit(actX, acty)
cross_val_score(bagging_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.59866199,  0.58892545,  0.5889391 ,  0.59686705,  0.5929941 ,
        0.68994534,  0.59068216,  0.70186457,  0.63712118,  0.57653291])

In [84]:
extraforest_act = ExtraTreesClassifier(n_estimators=150, random_state=0).fit(actX,acty)
cross_val_score(extraforest_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.66260411,  0.58974009,  0.5919519 ,  0.59710371,  0.59362214,
        0.69190685,  0.59203382,  0.70196924,  0.63570125,  0.57894952])

In [85]:
forest_act = RandomForestClassifier(n_estimators = 150).fit(actX,acty)
cross_val_score(forest_act, actX, acty, scoring='accuracy',cv=cv)

array([ 0.59942657,  0.59016789,  0.59176986,  0.59723569,  0.59252989,
        0.69185224,  0.59141033,  0.65345949,  0.63431318,  0.57873562])

In [ ]:
model_ada_act = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5, random_state=0), 
                               algorithm="SAMME", n_estimators=100).fit(actX,acty)
cross_val_score(model_ada_act, actX, acty, scoring='accuracy',cv=cv)

In [ ]:
model_grad_act = GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=0).fit(actX,acty)
cross_val_score(model_grad_act, actX, acty, scoring='accuracy',cv=cv)

In [39]:
model_xgb2 = xgboost.XGBClassifier(n_estimators=100, max_depth=10)
%time
Xx2 = model_xgb2.fit(actX,acty)

Wall time: 0 ns


In [40]:
for ix in range(len(actX.columns)):
    print (actX.columns[ix], Xx2.feature_importances_[ix])

date 0.435285
activity_category 0.0495369
char_1 0.0314591
char_2 0.0288091
char_3 0.020413
char_4 0.012804
char_5 0.0119644
char_6 0.0106263
char_7 0.0145882
char_8 0.0204655
char_9 0.0222759
char_10 0.341773


In [39]:
for idx in trainMerge.columns:
    if 'type 0' in list(trainMerge[idx].unique()):
        print (idx, 'type 0 ')
    else:pass

In [40]:
mergeX = trainMerge.drop(['people_id','activity_id','outcome'],axis = 1)
mergey = trainMerge['outcome']

In [41]:
for idx in mergeX.columns:
    mergeX[idx] = mergeX[idx].fillna('type 0')
    mergeX[idx] = LabelEncoder().fit_transform(mergeX[idx])

In [42]:
model_xgb3 = xgboost.XGBClassifier(n_estimators=100, max_depth=10)
%time
Xx3 = model_xgb3.fit(mergeX,mergey)

Wall time: 0 ns


In [43]:
for ix in range(len(mergeX.columns)):
    print (mergeX.columns[ix], Xx3.feature_importances_[ix])

date_x 0.130113
activity_category 0.00766686
char_1_x 0.00295051
char_2_x 0.00201171
char_3_x 0.00167643
char_4_x 0.00113997
char_5_x 0.0014082
char_6_x 0.000827037
char_7_x 0.000894095
char_8_x 0.00154231
char_9_x 0.00225759
char_10_x 0.0123385
char_1_y 0.00918682
group_1 0.235013
char_2_y 0.00221288
date_y 0.100809
char_3_y 0.0462694
char_4_y 0.0371049
char_5_y 0.0271805
char_6_y 0.0335956
char_7_y 0.0691806
char_8_y 0.030891
char_9_y 0.0293039
char_10_y 0.00657159
char_11 0.00605749
char_12 0.00507399
char_13 0.00677277
char_14 0.0056775
char_15 0.00569985
char_16 0.00402343
char_17 0.00534221
char_18 0.00502928
char_19 0.00364344
char_20 0.0037999
char_21 0.00359873
char_22 0.00384461
char_23 0.00444812
char_24 0.00558809
char_25 0.00858331
char_26 0.00476105
char_27 0.00464929
char_28 0.00151996
char_29 0.00543162
char_30 0.00397872
char_31 0.00596808
char_32 0.00556574
char_33 0.00362108
char_34 0.00518575
char_35 0.00527516
char_36 0.00315168
char_37 0.00301757
char_38 0.0785462

In [44]:
logimodelmerge = LogisticRegression().fit(mergeX,mergey)
cross_val_score(logimodelmerge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.85416648,  0.82759672,  0.81520418,  0.81911354,  0.81250085,
        0.86023238,  0.81934565,  0.86512932,  0.81039826,  0.8275239 ])

In [45]:
qdamerge = QuadraticDiscriminantAnalysis(store_covariances = True).fit(mergeX,mergey)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [46]:
cross_val_score(qdamerge, mergeX, mergey, scoring='accuracy',cv=cv)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:664: DeprecationWarning: 'store_covariances' was renamed to store_covariance in version 0.19 and will be removed in 0.21.
  DeprecationWarning)
C:\Users\pc\Anaconda3\lib\site-pa

array([ 0.73401447,  0.50883588,  0.5168321 ,  0.81564564,  0.8152679 ,
        0.63838182,  0.81602793,  0.63182375,  0.58066072,  0.82609942])

In [47]:
ldamerge = LinearDiscriminantAnalysis(n_components=3, solver="svd", store_covariance=True).fit(mergeX, mergey)
cross_val_score(ldamerge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.85410276,  0.82917139,  0.81703371,  0.82152106,  0.8174342 ,
        0.86068293,  0.8204106 ,  0.62653997,  0.82641345,  0.8262223 ])

In [48]:
clf_normmerge = GaussianNB().fit(mergeX,mergey)
cross_val_score(clf_normmerge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.73076503,  0.65989469,  0.67228268,  0.67994211,  0.67918663,
        0.75039253,  0.67420777,  0.7468427 ,  0.5932262 ,  0.66298941])

In [49]:
clf_bernmerge = BernoulliNB().fit(mergeX, mergey)
cross_val_score(clf_bernmerge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.72043872,  0.65106563,  0.65963983,  0.66719459,  0.66718549,
        0.7393107 ,  0.65178015,  0.7371717 ,  0.58233096,  0.65077891])

In [50]:
clf_multmerge = MultinomialNB().fit(mergeX,mergey)
cross_val_score(clf_multmerge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.6940791 ,  0.61508039,  0.59309877,  0.60315662,  0.60924593,
        0.70503666,  0.59053652,  0.45499684,  0.64247778,  0.5887252 ])

In [ ]:
tree1merge = DecisionTreeClassifier(criterion='entropy', max_depth=1).fit(mergeX, mergey)
cross_val_score(tree1merge, mergeX, mergey, scoring='accuracy',cv=cv)

array([ 0.85038456,  0.82158022,  0.81369323,  0.81952314,  0.81330184,
        0.85232263,  0.81772547,  0.87026747,  0.82280445,  0.82262241])

In [ ]:
baggingmerge = BaggingClassifier(DecisionTreeClassifier(), bootstrap_features=True, random_state=0).fit(mergeX, mergey)
cross_val_score(baggingmerge, mergeX, mergey, scoring='accuracy',cv=cv)

In [ ]:
extraforestmerge = ExtraTreesClassifier(n_estimators=150, random_state=0).fit(mergeX,mergey)
cross_val_score(extraforestmerge, mergeX, mergey, scoring='accuracy',cv=cv)

In [ ]:
forestmerge = RandomForestClassifier(n_estimators = 150).fit(mergeX,mergey)
cross_val_score(forestmerge, mergeX, mergey, scoring='accuracy',cv=cv)

In [ ]:
model_adamerge = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5, random_state=0), 
                               algorithm="SAMME", n_estimators=100).fit(mergeX,mergey)
cross_val_score(model_adamerge, mergeX, mergey, scoring='accuracy',cv=cv)

In [ ]:
model_gradmerge = GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=0).fit(mergeX,mergey)
cross_val_score(model_gradmerge, mergeX, mergey, scoring='accuracy',cv=cv)

In [ ]:
act_null_chr10 = act_Train[act_Train['char_10'].isnull()]
act_null_chr10

In [33]:
act_notnull_chr10 = act_Train[act_Train['char_10'].notnull()]
act_notnull_chr10

people_id   activity_id        date activity_category char_1 char_2  \
0           ppl_100  act2_1734928  2023-08-26            type 4    NaN    NaN   
1           ppl_100  act2_2434093  2022-09-27            type 2    NaN    NaN   
2           ppl_100  act2_3404049  2022-09-27            type 2    NaN    NaN   
3           ppl_100  act2_3651215  2023-08-04            type 2    NaN    NaN   
4           ppl_100  act2_4109017  2023-08-26            type 2    NaN    NaN   
5           ppl_100   act2_898576  2023-08-04            type 4    NaN    NaN   
6        ppl_100002  act2_1233489  2022-11-23            type 2    NaN    NaN   
7        ppl_100002  act2_1623405  2022-11-23            type 2    NaN    NaN   
8        ppl_100003  act2_1111598  2023-02-07            type 2    NaN    NaN   
9        ppl_100003  act2_1177453  2023-06-28            type 2    NaN    NaN   
10       ppl_100003   act2_133509  2022-08-10            type 4    NaN    NaN   
11       ppl_100003  act2_1408475  2023-03-02            type 4    NaN    NaN   
12       ppl_100003  act2_1610829  2022-09-13            type 2    NaN    NaN   
13       ppl_100003  act2_1688731  2023-02-10            type 4    NaN    NaN   
14       ppl_100003  act2_1961720  2023-06-28            type 4    NaN    NaN   
15       ppl_100003  act2_1988351  2022-08-23            type 2    NaN    NaN   
16       ppl_100003  act2_2198176  2022-08-16            type 2    NaN    NaN   
17       ppl_100003  act2_2437661  2023-02-02            type 2    NaN    NaN   
18       ppl_100003  act2_2476911  2023-03-02            type 2    NaN    NaN   
19       ppl_100003  act2_2557270  2022-08-30            type 4    NaN    NaN   
20       ppl_100003  act2_2581989  2023-02-21            type 2    NaN    NaN   
21       ppl_100003  act2_3116385  2023-02-15            type 2    NaN    NaN   
22       ppl_100003  act2_3159712  2022-08-30            type 2    NaN    NaN   
23       ppl_100003  act2_3292005  2023-05-03            type 2    NaN    NaN   
24       ppl_100003  act2_3461867  2023-08-02            type 2    NaN    NaN   
25       ppl_100003  act2_3468306  2023-03-02            type 4    NaN    NaN   
26       ppl_100003  act2_3867292  2023-02-10            type 2    NaN    NaN   
27       ppl_100003  act2_3990676  2023-08-30            type 4    NaN    NaN   
28       ppl_100003  act2_4102292  2023-08-30            type 2    NaN    NaN   
29       ppl_100003  act2_4160587  2023-02-21            type 2    NaN    NaN   
...             ...           ...         ...               ...    ...    ...   
2197261   ppl_99994  act2_2053669  2023-01-19            type 2    NaN    NaN   
2197262   ppl_99994  act2_2053762  2023-06-16            type 4    NaN    NaN   
2197263   ppl_99994  act2_2134893  2023-08-23            type 4    NaN    NaN   
2197264   ppl_99994  act2_2139237  2023-06-27            type 2    NaN    NaN   
2197265   ppl_99994  act2_2233766  2023-06-28            type 2    NaN    NaN   
2197266   ppl_99994  act2_2499779  2023-02-19            type 3    NaN    NaN   
2197267   ppl_99994  act2_2514377  2023-06-15            type 2    NaN    NaN   
2197268   ppl_99994  act2_2537795  2023-01-12            type 2    NaN    NaN   
2197269   ppl_99994  act2_2582736  2023-06-16            type 2    NaN    NaN   
2197270   ppl_99994  act2_2674371  2023-06-16            type 2    NaN    NaN   
2197271   ppl_99994  act2_2808953  2023-05-02            type 2    NaN    NaN   
2197272   ppl_99994  act2_2840212  2023-08-25            type 4    NaN    NaN   
2197273   ppl_99994  act2_2992386  2023-06-15            type 4    NaN    NaN   
2197274   ppl_99994  act2_3177773  2023-06-15            type 4    NaN    NaN   
2197275   ppl_99994  act2_3284072  2023-07-14            type 2    NaN    NaN   
2197276   ppl_99994  act2_3373847  2023-02-16            type 2    NaN    NaN   
2197277   ppl_99994  act2_3534467  2023-08-17            type 2    NaN    NaN   
2197278   ppl_99994  act2_3903321  2023-0